### ISSUE TITLE
[寻求帮助] 我想爬动漫之家的漫画

### ISSUE THREAD

**Issue by Z-fly** [Nymphxyz/nspider#1]
![image](https://user-images.githubusercontent.com/10470892/111636770-c1bc8800-8833-11eb-9afb-ea27af8c45a5.png)
动漫之家的漫画图片是通过JavaScript动态加载的，请问下nspider支持这种吗？

**Comment by Nymphxyz** [comment]
嗯，目前是不行的。正在考虑添加这个功能。

**Comment by Nymphxyz** [comment]
我看了这个网站，其实他的url是可以直接在返回的html里找到的。在这个script 下，使用正则表达式是可以提取的。
![image](https://user-images.githubusercontent.com/65056401/112281738-7fcf8e00-8cda-11eb-8be0-103bafbd2c46.png)
而且还都是有规律的。
![image](https://user-images.githubusercontent.com/65056401/112281843-9e358980-8cda-11eb-9988-7ac2975eebd9.png)

**Comment by Z-fly** [comment]
https://gist.github.com/Z-fly/029f83a863a70511c1ee41bd2dbac5d5
我自己写了个

**Comment by Z-fly** [comment]
@Nymphxyz 现在是想结合nspider来做，然后做个GUI 前后端一体化

**Comment by Nymphxyz** [comment]
> 
> 
> @Nymphxyz 现在是想结合nspider来做，然后做个GUI 前后端一体化
挺好的，我还想着可以再开一个仓库，然后以后谁写好的模板就放里面，大家都能直接用，不用再自己重写。

**Comment by Nymphxyz** [comment]
已解决。

**Comment by Nymphxyz** [comment]
已解决。
